[tools]
bun = "latest"
go = "latest"
java = "25"
node = "latest"
python = "latest"
rust = "latest"
uv = "latest"

bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
ripgrep = "latest"
shellcheck = "latest"
starship = "latest"
tmux = "latest"
zoxide = "latest"
ffmpeg = "latest"

[settings]
legacy_version_file = true
lockfile = false
locked = false
minimum_release_age = "0s"
